# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: idverification.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14idverification.proto\x12\x0eidVerification\"i\n\x18VerificationImageRequest\x12/\n\nimage_info\x18\x01 \x01(\x0b\x32\x19.idVerification.ImageInfoH\x00\x12\x14\n\nchunk_data\x18\x02 \x01(\x0cH\x00\x42\x06\n\x04\x64\x61ta\"P\n\tImageInfo\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x12\n\nimage_type\x18\x02 \x01(\t\x12\x1b\n\x13identification_type\x18\x03 \x01(\t\"G\n\x19VerificationImageResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x16\n\x0emessage_length\x18\x02 \x01(\r2\x83\x01\n\x0eIdVerification\x12q\n\x18ImageVerificationRequest\x12(.idVerification.VerificationImageRequest\x1a).idVerification.VerificationImageResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'idverification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VERIFICATIONIMAGEREQUEST']._serialized_start=40
  _globals['_VERIFICATIONIMAGEREQUEST']._serialized_end=145
  _globals['_IMAGEINFO']._serialized_start=147
  _globals['_IMAGEINFO']._serialized_end=227
  _globals['_VERIFICATIONIMAGERESPONSE']._serialized_start=229
  _globals['_VERIFICATIONIMAGERESPONSE']._serialized_end=300
  _globals['_IDVERIFICATION']._serialized_start=303
  _globals['_IDVERIFICATION']._serialized_end=434
# @@protoc_insertion_point(module_scope)
