# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import idverification_pb2 as idverification__pb2


class IdVerificationStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImageVerificationRequest = channel.stream_unary(
                '/idVerification.IdVerification/ImageVerificationRequest',
                request_serializer=idverification__pb2.VerificationImageRequest.SerializeToString,
                response_deserializer=idverification__pb2.VerificationImageResponse.FromString,
                )


class IdVerificationServicer(object):
    """The greeting service definition.
    """

    def ImageVerificationRequest(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdVerificationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ImageVerificationRequest': grpc.stream_unary_rpc_method_handler(
                    servicer.ImageVerificationRequest,
                    request_deserializer=idverification__pb2.VerificationImageRequest.FromString,
                    response_serializer=idverification__pb2.VerificationImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'idVerification.IdVerification', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IdVerification(object):
    """The greeting service definition.
    """

    @staticmethod
    def ImageVerificationRequest(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/idVerification.IdVerification/ImageVerificationRequest',
            idverification__pb2.VerificationImageRequest.SerializeToString,
            idverification__pb2.VerificationImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
